# Site Configuration
[site]
base_url = "https://damolaent.github.io"  # The full URL where site will be hosted

# Navigation Links
[links]
github = "https://github.com/damolaent"  # Replace with your GitHub profile link (e.g., "https://github.com/yourusername")
twitter = "https://twitter.com/Icon_The_Great"  # Replace with your Twitter profile link (e.g., "https://twitter.com/yourusername")

# Analytics
[analytics]
plausible_domain = ""  # Optional: set your domain here to enable Plausible (example: "myblog.com")
cloudflare_beacon_token = ""  # Optional â€” if set, inserts Cloudflare Analytics
